### ISSUE TITLE
Pelias ¡Doc Fest! 

### ISSUE THREAD

**Issue by kkowalsky** [pelias/pelias-doc#144]
editing and clarifying the documentation for Search to fix longstanding issues:

- [x] deleting (and creating redirects) for get-started page

- [x] [streamline text in index.md](https://github.com/pelias/pelias-doc/issues/141)

- [x] [edit photos and crop them](https://github.com/pelias/pelias-doc/issues/25)

- [x] [edit TOC order, wording](url)

- [x] [placement of terminology section](https://github.com/pelias/pelias-doc/issues/129)

- [x] [update rate limits](https://github.com/pelias/pelias-doc/issues/127)

- [x] [possible photo for index?](https://github.com/pelias/pelias-doc/issues/123)

**Comment by kkowalsky** [comment]
- [ ] update search tutorial

**Comment by kkowalsky** [comment]
not going to add a photo, for the index.md (want to have a consistent landing page feel for docs)
